package modelo;
// Generated 21 feb 2022 18:40:06 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private Integer codEstacion;
	private String nombre;
	private Set lineasEstacioneses = new HashSet(0);

	public Estaciones() {
	}

	public Estaciones(String nombre, Set lineasEstacioneses) {
		this.nombre = nombre;
		this.lineasEstacioneses = lineasEstacioneses;
	}

	public Integer getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(Integer codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLineasEstacioneses() {
		return this.lineasEstacioneses;
	}

	public void setLineasEstacioneses(Set lineasEstacioneses) {
		this.lineasEstacioneses = lineasEstacioneses;
	}

}
