package modelo;
// Generated 21 feb 2022 18:40:06 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lineas generated by hbm2java
 */
public class Lineas implements java.io.Serializable {

	private int codLinea;
	private String nombre;
	private Set lineasEstacioneses = new HashSet(0);

	public Lineas() {
	}

	public Lineas(int codLinea) {
		this.codLinea = codLinea;
	}

	public Lineas(int codLinea, String nombre, Set lineasEstacioneses) {
		this.codLinea = codLinea;
		this.nombre = nombre;
		this.lineasEstacioneses = lineasEstacioneses;
	}

	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLineasEstacioneses() {
		return this.lineasEstacioneses;
	}

	public void setLineasEstacioneses(Set lineasEstacioneses) {
		this.lineasEstacioneses = lineasEstacioneses;
	}

}
