package modelo;
// Generated 21 feb 2022 18:40:06 by Hibernate Tools 5.5.7.Final

/**
 * LineasEstacionesId generated by hbm2java
 */
public class LineasEstacionesId implements java.io.Serializable {

	private int codLinea;
	private int codEstacion;

	public LineasEstacionesId() {
	}

	public LineasEstacionesId(int codLinea, int codEstacion) {
		this.codLinea = codLinea;
		this.codEstacion = codEstacion;
	}

	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineasEstacionesId))
			return false;
		LineasEstacionesId castOther = (LineasEstacionesId) other;

		return (this.getCodLinea() == castOther.getCodLinea()) && (this.getCodEstacion() == castOther.getCodEstacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLinea();
		result = 37 * result + this.getCodEstacion();
		return result;
	}

}
