package modelo;
// Generated 21 feb 2022 18:40:06 by Hibernate Tools 5.5.7.Final

/**
 * LineasEstaciones generated by hbm2java
 */
public class LineasEstaciones implements java.io.Serializable {

	private LineasEstacionesId id;
	private Estaciones estaciones;
	private Lineas lineas;
	private int orden;

	public LineasEstaciones() {
	}

	public LineasEstaciones(LineasEstacionesId id, Estaciones estaciones, Lineas lineas, int orden) {
		this.id = id;
		this.estaciones = estaciones;
		this.lineas = lineas;
		this.orden = orden;
	}

	public LineasEstacionesId getId() {
		return this.id;
	}

	public void setId(LineasEstacionesId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Lineas getLineas() {
		return this.lineas;
	}

	public void setLineas(Lineas lineas) {
		this.lineas = lineas;
	}

	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
